#!/bin/bash
sbatch cc_jobs/data_generation/cc_job_n_profiles\=25000_n_voters\=50_n_alternative\=5_n_winners\=1_pref_dist\=\'IC\'_axioms\=\'all\'.sh
sbatch cc_jobs/data_generation/cc_job_n_profiles\=25000_n_voters\=50_n_alternative\=5_n_winners\=2_pref_dist\=\'IC\'_axioms\=\'all\'.sh
sbatch cc_jobs/data_generation/cc_job_n_profiles\=25000_n_voters\=50_n_alternative\=5_n_winners\=2_pref_dist\=\'IAC\'_axioms\=\'all\'.sh
sbatch cc_jobs/data_generation/cc_job_n_profiles\=25000_n_voters\=50_n_alternative\=5_n_winners\=2_pref_dist\=\'single_peaked_conitzer\'_axioms\=\'all\'.sh
sbatch cc_jobs/data_generation/cc_job_n_profiles\=25000_n_voters\=50_n_alternative\=5_n_winners\=2_pref_dist\=\'single_peaked_walsh\'_axioms\=\'all\'.sh
sbatch cc_jobs/data_generation/cc_job_n_profiles\=25000_n_voters\=50_n_alternative\=5_n_winners\=2_pref_dist\=\'euclidean__args__dimensions=3_-_space=gaussian_cube\'_axioms\=\'all\'.sh
sbatch cc_jobs/data_generation/cc_job_n_profiles\=25000_n_voters\=50_n_alternative\=5_n_winners\=2_pref_dist\=\'euclidean__args__dimensions=3_-_space=uniform_cube\'_axioms\=\'all\'.sh
sbatch cc_jobs/data_generation/cc_job_n_profiles\=25000_n_voters\=50_n_alternative\=5_n_winners\=3_pref_dist\=\'identity\'_axioms\=\'all\'.sh
sbatch cc_jobs/data_generation/cc_job_n_profiles\=25000_n_voters\=50_n_alternative\=5_n_winners\=3_pref_dist\=\'euclidean__args__dimensions=3_-_space=uniform_ball\'_axioms\=\'all\'.sh
sbatch cc_jobs/data_generation/cc_job_n_profiles\=25000_n_voters\=50_n_alternative\=5_n_winners\=3_pref_dist\=\'euclidean__args__dimensions=10_-_space=uniform_cube\'_axioms\=\'all\'.sh
sbatch cc_jobs/data_generation/cc_job_n_profiles\=25000_n_voters\=50_n_alternative\=5_n_winners\=4_pref_dist\=\'URN-R\'_axioms\=\'all\'.sh
sbatch cc_jobs/data_generation/cc_job_n_profiles\=25000_n_voters\=50_n_alternative\=5_n_winners\=4_pref_dist\=\'IC\'_axioms\=\'all\'.sh
sbatch cc_jobs/data_generation/cc_job_n_profiles\=25000_n_voters\=50_n_alternative\=5_n_winners\=4_pref_dist\=\'euclidean__args__dimensions=10_-_space=uniform_ball\'_axioms\=\'all\'.sh
sbatch cc_jobs/data_generation/cc_job_n_profiles\=25000_n_voters\=50_n_alternative\=5_n_winners\=4_pref_dist\=\'euclidean__args__dimensions=10_-_space=gaussian_cube\'_axioms\=\'all\'.sh
sbatch cc_jobs/data_generation/cc_job_n_profiles\=25000_n_voters\=50_n_alternative\=5_n_winners\=4_pref_dist\=\'euclidean__args__dimensions=3_-_space=uniform_cube\'_axioms\=\'all\'.sh
sbatch cc_jobs/data_generation/cc_job_n_profiles\=25000_n_voters\=50_n_alternative\=6_n_winners\=1_pref_dist\=\'stratification__args__weight=0.5\'_axioms\=\'all\'.sh
sbatch cc_jobs/data_generation/cc_job_n_profiles\=25000_n_voters\=50_n_alternative\=6_n_winners\=1_pref_dist\=\'IAC\'_axioms\=\'all\'.sh
sbatch cc_jobs/data_generation/cc_job_n_profiles\=25000_n_voters\=50_n_alternative\=6_n_winners\=1_pref_dist\=\'identity\'_axioms\=\'all\'.sh
sbatch cc_jobs/data_generation/cc_job_n_profiles\=25000_n_voters\=50_n_alternative\=6_n_winners\=2_pref_dist\=\'IC\'_axioms\=\'all\'.sh
sbatch cc_jobs/data_generation/cc_job_n_profiles\=25000_n_voters\=50_n_alternative\=6_n_winners\=2_pref_dist\=\'identity\'_axioms\=\'all\'.sh
sbatch cc_jobs/data_generation/cc_job_n_profiles\=25000_n_voters\=50_n_alternative\=6_n_winners\=2_pref_dist\=\'euclidean__args__dimensions=3_-_space=gaussian_cube\'_axioms\=\'all\'.sh
sbatch cc_jobs/data_generation/cc_job_n_profiles\=25000_n_voters\=50_n_alternative\=6_n_winners\=3_pref_dist\=\'IC\'_axioms\=\'all\'.sh
sbatch cc_jobs/data_generation/cc_job_n_profiles\=25000_n_voters\=50_n_alternative\=6_n_winners\=3_pref_dist\=\'MALLOWS-RELPHI-R\'_axioms\=\'all\'.sh
sbatch cc_jobs/data_generation/cc_job_n_profiles\=25000_n_voters\=50_n_alternative\=6_n_winners\=3_pref_dist\=\'euclidean__args__dimensions=10_-_space=gaussian_ball\'_axioms\=\'all\'.sh
sbatch cc_jobs/data_generation/cc_job_n_profiles\=25000_n_voters\=50_n_alternative\=6_n_winners\=3_pref_dist\=\'euclidean__args__dimensions=10_-_space=uniform_ball\'_axioms\=\'all\'.sh
sbatch cc_jobs/data_generation/cc_job_n_profiles\=25000_n_voters\=50_n_alternative\=6_n_winners\=4_pref_dist\=\'URN-R\'_axioms\=\'all\'.sh
sbatch cc_jobs/data_generation/cc_job_n_profiles\=25000_n_voters\=50_n_alternative\=6_n_winners\=4_pref_dist\=\'IC\'_axioms\=\'all\'.sh
sbatch cc_jobs/data_generation/cc_job_n_profiles\=25000_n_voters\=50_n_alternative\=6_n_winners\=4_pref_dist\=\'IAC\'_axioms\=\'all\'.sh
sbatch cc_jobs/data_generation/cc_job_n_profiles\=25000_n_voters\=50_n_alternative\=6_n_winners\=4_pref_dist\=\'MALLOWS-RELPHI-R\'_axioms\=\'all\'.sh
sbatch cc_jobs/data_generation/cc_job_n_profiles\=25000_n_voters\=50_n_alternative\=6_n_winners\=4_pref_dist\=\'euclidean__args__dimensions=3_-_space=uniform_ball\'_axioms\=\'all\'.sh
sbatch cc_jobs/data_generation/cc_job_n_profiles\=25000_n_voters\=50_n_alternative\=6_n_winners\=4_pref_dist\=\'euclidean__args__dimensions=3_-_space=gaussian_cube\'_axioms\=\'all\'.sh
sbatch cc_jobs/data_generation/cc_job_n_profiles\=25000_n_voters\=50_n_alternative\=6_n_winners\=5_pref_dist\=\'IC\'_axioms\=\'all\'.sh
sbatch cc_jobs/data_generation/cc_job_n_profiles\=25000_n_voters\=50_n_alternative\=7_n_winners\=1_pref_dist\=\'stratification__args__weight=0.5\'_axioms\=\'all\'.sh
sbatch cc_jobs/data_generation/cc_job_n_profiles\=25000_n_voters\=50_n_alternative\=7_n_winners\=1_pref_dist\=\'URN-R\'_axioms\=\'all\'.sh
sbatch cc_jobs/data_generation/cc_job_n_profiles\=25000_n_voters\=50_n_alternative\=7_n_winners\=1_pref_dist\=\'IC\'_axioms\=\'all\'.sh
sbatch cc_jobs/data_generation/cc_job_n_profiles\=25000_n_voters\=50_n_alternative\=7_n_winners\=1_pref_dist\=\'IAC\'_axioms\=\'all\'.sh
sbatch cc_jobs/data_generation/cc_job_n_profiles\=25000_n_voters\=50_n_alternative\=7_n_winners\=1_pref_dist\=\'identity\'_axioms\=\'all\'.sh
sbatch cc_jobs/data_generation/cc_job_n_profiles\=25000_n_voters\=50_n_alternative\=7_n_winners\=1_pref_dist\=\'single_peaked_walsh\'_axioms\=\'all\'.sh
sbatch cc_jobs/data_generation/cc_job_n_profiles\=25000_n_voters\=50_n_alternative\=7_n_winners\=1_pref_dist\=\'euclidean__args__dimensions=3_-_space=gaussian_ball\'_axioms\=\'all\'.sh
sbatch cc_jobs/data_generation/cc_job_n_profiles\=25000_n_voters\=50_n_alternative\=7_n_winners\=1_pref_dist\=\'euclidean__args__dimensions=10_-_space=gaussian_ball\'_axioms\=\'all\'.sh
sbatch cc_jobs/data_generation/cc_job_n_profiles\=25000_n_voters\=50_n_alternative\=7_n_winners\=1_pref_dist\=\'euclidean__args__dimensions=10_-_space=uniform_ball\'_axioms\=\'all\'.sh
sbatch cc_jobs/data_generation/cc_job_n_profiles\=25000_n_voters\=50_n_alternative\=7_n_winners\=1_pref_dist\=\'euclidean__args__dimensions=3_-_space=gaussian_cube\'_axioms\=\'all\'.sh
sbatch cc_jobs/data_generation/cc_job_n_profiles\=25000_n_voters\=50_n_alternative\=7_n_winners\=1_pref_dist\=\'euclidean__args__dimensions=3_-_space=uniform_cube\'_axioms\=\'all\'.sh
sbatch cc_jobs/data_generation/cc_job_n_profiles\=25000_n_voters\=50_n_alternative\=7_n_winners\=1_pref_dist\=\'euclidean__args__dimensions=10_-_space=uniform_cube\'_axioms\=\'all\'.sh
sbatch cc_jobs/data_generation/cc_job_n_profiles\=25000_n_voters\=50_n_alternative\=7_n_winners\=2_pref_dist\=\'identity\'_axioms\=\'all\'.sh
sbatch cc_jobs/data_generation/cc_job_n_profiles\=25000_n_voters\=50_n_alternative\=7_n_winners\=2_pref_dist\=\'euclidean__args__dimensions=3_-_space=gaussian_cube\'_axioms\=\'all\'.sh
sbatch cc_jobs/data_generation/cc_job_n_profiles\=25000_n_voters\=50_n_alternative\=7_n_winners\=3_pref_dist\=\'MALLOWS-RELPHI-R\'_axioms\=\'all\'.sh
sbatch cc_jobs/data_generation/cc_job_n_profiles\=25000_n_voters\=50_n_alternative\=7_n_winners\=3_pref_dist\=\'single_peaked_walsh\'_axioms\=\'all\'.sh
sbatch cc_jobs/data_generation/cc_job_n_profiles\=25000_n_voters\=50_n_alternative\=7_n_winners\=3_pref_dist\=\'euclidean__args__dimensions=10_-_space=uniform_ball\'_axioms\=\'all\'.sh
sbatch cc_jobs/data_generation/cc_job_n_profiles\=25000_n_voters\=50_n_alternative\=7_n_winners\=4_pref_dist\=\'stratification__args__weight=0.5\'_axioms\=\'all\'.sh
sbatch cc_jobs/data_generation/cc_job_n_profiles\=25000_n_voters\=50_n_alternative\=7_n_winners\=4_pref_dist\=\'IC\'_axioms\=\'all\'.sh
sbatch cc_jobs/data_generation/cc_job_n_profiles\=25000_n_voters\=50_n_alternative\=7_n_winners\=4_pref_dist\=\'single_peaked_conitzer\'_axioms\=\'all\'.sh
sbatch cc_jobs/data_generation/cc_job_n_profiles\=25000_n_voters\=50_n_alternative\=7_n_winners\=4_pref_dist\=\'euclidean__args__dimensions=3_-_space=gaussian_cube\'_axioms\=\'all\'.sh
sbatch cc_jobs/data_generation/cc_job_n_profiles\=25000_n_voters\=50_n_alternative\=7_n_winners\=4_pref_dist\=\'euclidean__args__dimensions=10_-_space=gaussian_cube\'_axioms\=\'all\'.sh
sbatch cc_jobs/data_generation/cc_job_n_profiles\=25000_n_voters\=50_n_alternative\=7_n_winners\=5_pref_dist\=\'single_peaked_conitzer\'_axioms\=\'all\'.sh
sbatch cc_jobs/data_generation/cc_job_n_profiles\=25000_n_voters\=50_n_alternative\=7_n_winners\=5_pref_dist\=\'euclidean__args__dimensions=3_-_space=uniform_ball\'_axioms\=\'all\'.sh
sbatch cc_jobs/data_generation/cc_job_n_profiles\=25000_n_voters\=50_n_alternative\=7_n_winners\=6_pref_dist\=\'IAC\'_axioms\=\'all\'.sh
sbatch cc_jobs/data_generation/cc_job_n_profiles\=25000_n_voters\=50_n_alternative\=7_n_winners\=6_pref_dist\=\'identity\'_axioms\=\'all\'.sh
sbatch cc_jobs/data_generation/cc_job_n_profiles\=25000_n_voters\=50_n_alternative\=7_n_winners\=6_pref_dist\=\'single_peaked_conitzer\'_axioms\=\'all\'.sh
sbatch cc_jobs/data_generation/cc_job_n_profiles\=25000_n_voters\=50_n_alternative\=7_n_winners\=6_pref_dist\=\'euclidean__args__dimensions=3_-_space=uniform_ball\'_axioms\=\'all\'.sh
